spring:
  application:
    name: favorite-places-service
  datasource:
    url: jdbc:h2:mem:favorite_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8086

user-service:
  url: http://localhost:8081

logging:
  level:
    com.taxi: DEBUG
